# Alembic configuration file

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(rev)s_%%(created_at)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to the constructor of datetime.datetime
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of the revision file
# (template 1 supports unlimited length of string).
# (template 2 supports a maximum length of 40 characters).
# template1: %%(rev)s_%%(slug)s[%%(length)s]
# template2: %%(rev)s[%%(length)s]_%%(slug)s
# truncate_slug_length =

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure [loggers]
# Keys in loggers:
# qualname - the logger name. This is used by the `logger=` key in [logger_*] references
# to determine which logger config gets applied to which logger
#
#
# [logger_sqlalchemy]
# qualname = sqlalchemy.engine
# level = WARN
# handlers =
#     console_sql
#
# [logger_alembic]
# qualname = alembic
# level = INFO
# handlers =
#
# loggers =
#     sqlalchemy.engine
#     alembic


# log format and propagation format specs
# %(asctime)s %(levelname)s %(name)s %(message)s
# datefmt = %H:%M:%S


# log handlers
# Keys in handlers:
# qualname - the logger name. This is used by the `logger=` key in [logger_*] references
# to determine which logger config gets applied to which logger
#
# keys = console

# console -
# stream handler used in logging configuration shows log output
# stream format and propagation format specs %(message)s
# datefmt =

# add the handler to the root logger
# qualname =
# level = NOTSET
# handlers = console


# use the provided logging.config module to load config from .env file.
# disable_existing_loggers = false

# Migration environment
[sqlalchemy.url]
sqlalchemy.url = driver://user:password@localhost/dbname

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
